language: generic
sudo: required
services: 
    - docker

before_install:
    - docker build -t kstime/docker-react -f Dockerfile.dev . 

script: 
    - docker run -e CI=true kstime/docker-react npm run test